name: Trigger auto deployment for ai-agent-school

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ai-agent-school-AutoDeployTrigger-6e1f6648-8066-4e2c-92c9-c3972a22a48b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AIAGENTSCHOOL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AIAGENTSCHOOL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AIAGENTSCHOOL_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.AIAGENTSCHOOL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AIAGENTSCHOOL_REGISTRY_PASSWORD }}
          containerAppName: ai-agent-school
          resourceGroup: Default-ActivityLogAlerts
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


